### ISSUE TITLE
Не работает дата

### ISSUE THREAD

**Issue by SpriteCT** [TaxedoMax/stasks#4]
Я что-то нажал и оно не работает. Почините пожалуйста. Я очень хочу пользоваться вашим приложением

**Comment by TaxedoMax** [comment]
This issue already exists: [https://github.com/TaxedoMax/stasks/issues/2](url)

**Comment by TaxedoMax** [comment]
This issue already exists: [https://github.com/TaxedoMax/stasks/issues/2](url)
