### ISSUE TITLE
Сложно листать

### ISSUE THREAD

**Issue by pilllbox** [TaxedoMax/stasks#7]
Когда много задач и они не помещаются на экране телефона, для доступа к нижним задачам нужно пролистать. Это становится почти невозможно, потому что вместо пролистывания ты хватаешься за задачу и перетаскиваешь ее. 
Может стоит сделать какую-то область на экране, по которой можно будет спокойно пролистать, не меняя задачи местами.

**Comment by TaxedoMax** [comment]
Перетягиваемая область перенесена в центр экрана
